### ISSUE TITLE
how to store gc<T> in std::function

### ISSUE THREAD

**Issue by kritzikratzi** [crazybie/tgc#2]
hi! 

i have been working and maintaining a ui library for quite a long time, and have been considering switching over to GC  for a few times, but always failed. at the moment i'm making another attempt to investigate GCs, and where they can and cannot work. 

with your library i'm struggling how i would deal with collected pointers captured by `std::function`, ie. something along the lines of `capture_ptr->event = [captured_ptr](){...}` in the simplest case (the capture doesn't have to loop back on it self, but this is the simplest case i can think of). 

here is some code i'm trying: 

	#include "tgc.h"
	#include <iostream>

	using namespace tgc;

	struct Container{
		Container(){ std::cout << "create container at " << this << std::endl; }
		virtual ~Container(){ std::cout << "delete container at " << this << std::endl; }

		std::function<void()> event;
		gc<std::function<void()>> gc_event;
	};

	void test3_not_ok(){
		std::cout << "---- TEST 3 (NOT OK) -----------" << std::endl;
		{
			auto c = gc_new<Container>();
			// trapping c in the std::function creates a non-resolvable cycle
			c->event = [c](){};
		}
		
		gc_collect(); // ... so c does not get collected
		gc_dumpStats();
	}

	void test4_not_ok(){
		std::cout << "---- TEST 4 (NOT OK) -----------" << std::endl;
		{
			auto c = gc_new<Container>();
			// this also doesn't help
			c->gc_event = gc_new<std::function<void()>>([c](){});
		}
		
		gc_collect(); // ... so c does not get collected
		gc_dumpStats();
	}

	int main(){
		test3_not_ok();
		test4_not_ok();

		return 0;
	}

the output i get is: 

	---- TEST 3 (NOT OK) -----------
	create container at 0x100508e80
	
	# i would want a delete here, but am not getting it
	
	
	========= [gc] ========
	[total pointers ]   2
	[total meta     ]   1
	[total gray meta]   0
	[live objects   ]   1
	[last freed objs]   0
	[collector state] Sweeping
	=======================
	---- TEST 4 (NOT OK) -----------
	create container at 0x100508fc0

	# same, i would want a delete here...

	========= [gc] ========
	[total pointers ]   4
	[total meta     ]   3
	[total gray meta]   2
	[live objects   ]   3
	[last freed objs]   0
	[collector state] LeafMarking
	=======================
	
	# program exits, so all the gc objects get cleaned up (too late)
	
	delete container at 0x100508fc0
	delete container at 0x100508e80
	Program ended with exit code: 0

do you have any advice how i would capture pointers in lambads, but still be able to discard cyclic objects that aren't "really" referenced anymore?

**Comment by kritzikratzi** [comment]
oh. i just found about gc_function when looking through the asio sample (not sure how i missed it in the first place). 

here is my updated code

	#include "tgc.h"
	#include <iostream>

	using namespace tgc;

	struct Container{
		Container(){ std::cout << "create container at " << this << std::endl; }
		virtual ~Container(){ std::cout << "delete container at " << this << std::endl; }

		std::function<void()> event;
		gc_function<void()> gc_event;
	};



	void test3_not_ok(){
		std::cout << "---- TEST 3 (NOT OK) -----------" << std::endl;
		{
			auto c = gc_new<Container>();
			// trapping c in the std::function creates a non-resolvable cycle
			c->event = [c](){};
		}
		
		gc_collect(); // ... so c does not get collected
		gc_dumpStats();
	}

	void test4_ok(){
		std::cout << "---- TEST 4 (OK) -----------" << std::endl;
		{
			auto c = gc_new<Container>();
			// this also doesn't help
			c->gc_event = [c](){};
		}
		
		gc_collect(); // ... so c does not get collected
		gc_dumpStats();
	}


	int main(){
		test3_not_ok();
		test4_ok();

		return 0;
	}

and output: 

	---- TEST 3 (NOT OK) -----------
	create container at 0x10190b240

	# delete missing. not what i want, but expected
	
	========= [gc] ========
	[total pointers ]   2
	[total meta     ]   1
	[total gray meta]   0
	[live objects   ]   1
	[last freed objs]   0
	[collector state] Sweeping
	=======================
	---- TEST 4 (OK) -----------
	create container at 0x10190b340
	delete container at 0x10190b340

	# delete works, hurray :) 

	========= [gc] ========
	[total pointers ]   2
	[total meta     ]   1
	[total gray meta]   1
	[live objects   ]   1
	[last freed objs]   2
	[collector state] LeafMarking
	=======================
	delete container at 0x10190b240
	Program ended with exit code: 0

**Comment by crazybie** [comment]
Hi,

Pls try to use the gc_function instead of the std::function.
Besides, you must use the correspoinding wrapper of std containers to ensure memories are tracable to the gc.
You can not mix the std containers with tgc containers, that's the limitation of tgc.



***@***.***
 
From: hansi raber
Date: 2022-01-08 21:08
To: crazybie/tgc
CC: Subscribed
Subject: [crazybie/tgc] how to store gc<T> in std::function (Issue #2)
hi!
i have been working and maintaining a ui library for quite a long time, and have been considering switching over to GC for a few times, but always failed. at the moment i'm making another attempt to investigate GCs, and where they can and cannot work.
with your library i'm struggling how i would deal with collected pointers captured by std::function, ie. something along the lines of capture_ptr->event = [captured_ptr](){...} in the simplest case (the capture doesn't have to loop back on it self, but this is the simplest case i can think of).
here is some code i'm trying:
#include "tgc.h"
#include <iostream>
using namespace tgc;
struct Container{
	Container(){ std::cout << "create container at " << this << std::endl; }
	virtual ~Container(){ std::cout << "delete container at " << this << std::endl; }
	std::function<void()> event;
	gc<std::function<void()>> gc_event;
};
void test3_not_ok(){
	std::cout << "---- TEST 3 (NOT OK) -----------" << std::endl;
	{
		auto c = gc_new<Container>();
		// trapping c in the std::function creates a non-resolvable cycle
		c->event = [c](){};
	}
	
	gc_collect(); // ... so c does not get collected
	gc_dumpStats();
}
void test4_not_ok(){
	std::cout << "---- TEST 4 (NOT OK) -----------" << std::endl;
	{
		auto c = gc_new<Container>();
		// this also doesn't help
		c->gc_event = gc_new<std::function<void()>>([c](){});
	}
	
	gc_collect(); // ... so c does not get collected
	gc_dumpStats();
}
int main(){
	test3_not_ok();
	test4_not_ok();
	return 0;
}

do you have any advice how i would capture pointers in lambads, but still be able to discard cyclic objects that aren't "really" referenced anymore?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
